% Script generated by Brainstorm (09-May-2023)

% % Input files
% sSubject = bst_get('ProtocolSubjects') ; 
% SubjectNames = {sSubject.Subject.Name} ; 
% SubjectNames(contains(SubjectNames,'Group_analysis')) = [] ;
% SubjectGroup1 = SubjectNames(contains(SubjectNames,["T6","T8","T10"])) ; 
% SubjectGroup2 = SubjectNames(contains(SubjectNames,["T18","T24"])) ; 

% Start a new report
bst_report('Start', []);

% Process: Select data files in: */DEV1-STD1/_T8
sFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
    'subjectname',   SubjectGroup1, ...
    'condition',     'DEV1-STD1', ...
    'tag',           '', ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0);

sFilesG1 = sFiles(contains({sFiles.FileName},["_T6","_T8","_T10"])); 
sFilesG2 = sFiles(contains({sFiles.FileName},["_T18","_T24"])); 

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);
% bst_report('Email', ReportFile, username, to, subject, isFullReport);

% Delete temporary files
% gui_brainstorm('EmptyTempFolder');

